### ISSUE TITLE
From CanDI import candi

### ISSUE THREAD

**Issue by zenglongjin** [GilbertLabUCSF/CanDI#29]
Dear Gilbert:
When we used this function in python3, the following error has occurred:
`DuplicateOptionError                      Traceback (most recent call last)
<ipython-input-8-e51eff7b0ca2> in <module>
      6 import tqdm
      7 sys.path.append("C:/Users/Asus/anaconda3/pkgs/CanDI-master/CanDI")
----> 8 from CanDI import candi

C:/Users/Asus/anaconda3/pkgs/CanDI-master\CanDI\candi\__init__.py in <module>
      1 from CanDI.candi import data
----> 2 data = data.Data() #Global object data instantiated on import required for access by GeneQuery Objects
      3 from CanDI.candi.candi import (Gene, CellLine, Organelle, Cancer, CellLineCluster, GeneCluster)
      4 

C:/Users/Asus/anaconda3/pkgs/CanDI-master\CanDI\candi\data.py in __init__(self)
     21 
     22         parser = configparser.ConfigParser() #parses config for data sources
---> 23         parser.read(config_path)
     24 
     25         self._parser = parser

~\anaconda3\lib\configparser.py in read(self, filenames, encoding)
    695             try:
    696                 with open(filename, encoding=encoding) as fp:
--> 697                     self._read(fp, filename)
    698             except OSError:
    699                 continue

~\anaconda3\lib\configparser.py in _read(self, fp, fpname)
   1091                         if (self._strict and
   1092                             (sectname, optname) in elements_added):
-> 1093                             raise DuplicateOptionError(sectname, optname,
   1094                                                        fpname, lineno)
   1095                         elements_added.add((sectname, optname))

DuplicateOptionError: While reading from WindowsPath('C:/Users/Asus/anaconda3/pkgs/CanDI-master/CanDI/setup/data/config.ini') [line 49]: option 'c' in section 'formatted' already exists`
Thank you very much for your attention and consideration.

**Comment by abearab** [comment]
Thanks for your interest in using CanDI. 

We haven't really tested this package in windows, are you using [conda](https://docs.conda.io/en/latest/) by any chance?

**Comment by zenglongjin** [comment]
Yes, we are limited on windows, next try Linux system. It would be great if you could test windows.

**Comment by zenglongjin** [comment]
I'm sorry to be new python users, but I noticed what seemed to be a failed read of **config.ini**
`parser = configparser.ConfigParser()
parser.read('C:/Users/Asus/anaconda3/pkgs/CanDI-master/CanDI/setup/data/config.ini')
DuplicateOptionError: While reading from WindowsPath('C:/Users/Asus/anaconda3/pkgs/CanDI-master/CanDI/setup/data/config.ini') [line 49]: option 'c' in section 'formatted' already exists`

**Comment by zenglongjin** [comment]
I'm sorry to be new python users, but I noticed what seemed to be a failed read of **config.ini**
`parser = configparser.ConfigParser()
parser.read('C:/Users/Asus/anaconda3/pkgs/CanDI-master/CanDI/setup/data/config.ini')
DuplicateOptionError: While reading from WindowsPath('C:/Users/Asus/anaconda3/pkgs/CanDI-master/CanDI/setup/data/config.ini') [line 49]: option 'c' in section 'formatted' already exists`

**Comment by abearab** [comment]
Can you check your python version, too? Also, check "which" available python in your system is working when you run the problematic command. I'm not sure how you are using your conda environments. It's important to make sure you are setting up your Python interpreter correctly including dependencies. To be clear, when you run this line described in the README `conda env create -f CanDI/candi.yml -n candi`, then you must activate your `candi` environment and use python there.
