### ISSUE TITLE
Fix `candi-install` errors

### ISSUE THREAD

**Issue by abearab** [GilbertLabUCSF/CanDI#41]

**Comment by abearab** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data_gilbert/home/aarab/anaconda3/envs/mamba/envs/candi-kg/lib/python3.9/site-packages/CanDI/candi/__init__.py", line 2, in <module>
    data = data.Data() #Global object data instantiated on import required for access by GeneQuery Objects
  File "/data_gilbert/home/aarab/anaconda3/envs/mamba/envs/candi-kg/lib/python3.9/site-packages/CanDI/candi/data.py", line 27, in __init__
    self._init_sources()
  File "/data_gilbert/home/aarab/anaconda3/envs/mamba/envs/candi-kg/lib/python3.9/site-packages/CanDI/candi/data.py", line 42, in _init_sources
    for option in self._parser["data_paths"]:
  File "/data_gilbert/home/aarab/anaconda3/envs/mamba/envs/candi-kg/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'data_paths'
```

**Comment by Yogiski** [comment]
Get this error when I try and run the install script. 
Happy to take this issue on. 

```
(candi) yogi@Christophers-MacBook-Pro CanDI % python3 CanDI/setup/install.py
Traceback (most recent call last):
  File "/Users/yogi/Projects/CanDI/CanDI/setup/install.py", line 2, in <module>
    from .manager import Manager
```

**Comment by Yogiski** [comment]
Also getting that circular import error when i do:
```
from CanDI import candi
```
Ran into this before but cant remember what was happening.  I'll include the fix in this branch.

**Comment by abearab** [comment]
@Yogiski – Hi Chris, Thanks for looking into this! I think there are some specific package design choices that you know and it would be best if you could look into this. Let me know if you need my help and I'll be more than happy to talk more about it. 

https://github.com/GilbertLabUCSF/CanDI/issues/41#issuecomment-2067752101 – I also couldn't load `Manager` module. I'm not sure what is the reason. I might have caused the issue on my end haha

There are a few details that I have learned:
1. My understanding is that the default "data" path is problematic as implemented. I made a PyPI for CanDI so I think we need to split the data path from the place CanDI as a package will be installed with `pip` command. I ran into issues with setting up CanDI using your install command since this will be the relative environment path (I don't remember the exact details). Generally, this will be hard to find as we move forward. I suggest using a local data path to locate datasets with a default location but giving the option so users can change it.

2. I proposed the option to collect data from [CanDI dataverse](https://doi.org/10.1186/s13073-021-00987-8) which is a place to keep any compatible data with CanDI and we can upload them ourself overtime. I think this is more reliable compared to the current implementation. However, it's cool if we can have the depmap API to collect latest data from depmap.
    - #37 
    - #34 
3. Since we published CanDI I have learned about [TDC](https://github.com/mims-harvard/TDC/) and [gget](https://github.com/pachterlab/gget/); also I developed [ScreenPro2](https://github.com/ArcInstitute/ScreenPro2). I think these two will be cool toolboxes to make CanDI compatible with them. For instance, gget can be a light dependency we can add for useful APIs, etc. TDC will be useful to use CanDI together with other datasets for different tasks (I have done this at least once, plz see [this notebook](https://github.com/GilbertLabUCSF/Decitabine-treatment/blob/main/DAC_combo.ipynb)). Also, you may see these discussions.
    - https://github.com/mims-harvard/TDC/issues/216
    - https://github.com/pachterlab/gget/pull/124

**Comment by abearab** [comment]
> Also getting that circular import error when i do:
> 
> ```
> from CanDI import candi
> ```
> 
> Ran into this before but cant remember what was happening. I'll include the fix in this branch.

It would be wonderful if you could fix this, I won't have time now for this but I'll be happy to take care of other issues in parallel.

**Comment by abearab** [comment]
> Get this error when I try and run the install script. Happy to take this issue on.
> 
> ```
> (candi) yogi@Christophers-MacBook-Pro CanDI % python3 CanDI/setup/install.py
> Traceback (most recent call last):
>   File "/Users/yogi/Projects/CanDI/CanDI/setup/install.py", line 2, in <module>
>     from .manager import Manager
> ```

I think I just needed to use `from manager import Manager`!
